export interface RawDocProject {
  row: number;
  studentName: string;
  title: string;
  supervisorName: string;
  description: string;
}

export const OFFICIAL_STARTUPS_LIST: RawDocProject[] = [
  {
    row: 1,
    studentName: 'Muzaffarov Sarvar Sanjar o‘g‘li',
    title: 'Zig‘ir urug‘i kunjarasidan funksional oziq-ovqat mahsulotlari ishlab chiqish',
    supervisorName: 'B.Jumayev',
    description: 'Zig‘ir urug‘i kunjarasini qayta ishlab, oqsil va biologik faol moddalarga boy funksional oziq-ovqat mahsulotlari olishga qaratilgan. Qishloq xo‘jaligi xomashyosi chiqindilaridan samarali foydalanish va sog‘lom ovqatlanish mahsulotlariga talabni qondirish bilan dolzarb.',
  },
  {
    row: 2,
    studentName: 'Ernazarova Malika Erkin qizi',
    title: 'Avtomobillarga metan gazi quyish shaxobchalarida navbat tizimini raqamlashtirish platformasi',
    supervisorName: 'B.Abdullayev',
    description: 'Metan gaz quyish shoxobchalaridagi navbatlarni raqamli boshqarish va mijozlarga qulay xizmat ko‘rsatish platformasi. Vaqtni tejash, navbatlarni kamaytirish va xizmat ko‘rsatish samaradorligini oshirish zarurati bilan dolzarb.',
  },
  {
    row: 3,
    studentName: 'O‘ktamova Zilola O‘ktam qizi',
    title: 'Aqilli mahalla - xavfsizlik tizimi: maktab, mahalla, oila nazorat zanjiri tahlili platformasi',
    supervisorName: 'B.Abdullayev',
    description: 'Maktab, mahalla va oila o‘rtasidagi xavfsizlik nazoratini yagona raqamli platformada tahlil qilish tizimi. Voyaga yetmaganlar xavfsizligini ta’minlash va mas’ullar o‘rtasida tezkor axborot almashinuvini yaxshilash bilan dolzarb.',
  },
  {
    row: 4,
    studentName: 'Hazratqulova Ro’zigul Qurbonali qizi',
    title: 'Aqlli Qishloq – Aholi xonadonlarida qishloq xo’jaligi samaradorligini oshiruvchi intellektual monitoring tizimi platformasi',
    supervisorName: 'B.Abdullayev',
    description: 'Xonadonlarda qishloq xo‘jaligi faoliyatini monitoring qilish, resurslardan foydalanishni kuzatish va samaradorlikni oshirishga xizmat qiluvchi intellektual platforma. Aqlli qishloq xo‘jaligi yondashuvlarini rivojlantirish bilan dolzarb.',
  },
  {
    row: 5,
    studentName: 'Julanov Shaxriyor Farhodovich',
    title: 'Metodlarni raqamli muhitga moslashtirish platformasi',
    supervisorName: 'B.Abdullayev',
    description: 'Ta’lim metodlarini raqamli muhitga moslashtirish va ulardan foydalanishni tizimlashtirishga mo‘ljallangan platforma. Raqamli ta’lim vositalaridan samarali foydalanish va o‘qitish sifatini oshirish ehtiyoji bilan dolzarb.',
  },
  {
    row: 6,
    studentName: 'Saydullaev Zoxidjon Farhod o‘g‘li',
    title: 'Matn asosida rasm va video yaratish platformasi',
    supervisorName: 'B.Abdullayev',
    description: 'Matnli tavsif asosida rasm va video yaratishga mo‘ljallangan raqamli platforma. Kontent tayyorlash jarayonini tezlashtirish va zamonaviy raqamli ijodiy vositalardan foydalanish imkoniyatini kengaytirish bilan dolzarb.',
  },
  {
    row: 7,
    studentName: 'Adhamov Tohir Zokir o‘g‘li',
    title: 'Ingliz tilini raqamlashtirish orqali o‘qitish platformasi',
    supervisorName: 'B.Abdullayev',
    description: 'Ingliz tilini raqamli vositalar orqali o‘qitish va o‘rganishni tashkil etuvchi platforma. Til o‘rganishni interaktiv va qulay shaklga o‘tkazish hamda ta’lim resurslaridan foydalanishni kengaytirish bilan dolzarb.',
  },
  {
    row: 8,
    studentName: 'Tuxtaboyev Ibroxim Muhiddin o‘g‘li',
    title: 'Fizika fanining labaratoriyasini simulyatsiyalash platformasi',
    supervisorName: 'B.Abdullayev',
    description: 'Fizika laboratoriya mashg‘ulotlarini virtual muhitda simulyatsiya qilish platformasi. Qimmat yoki cheklangan laboratoriya jihozlarisiz tajribalarni bajarish va amaliy ko‘nikmalarni rivojlantirish bilan dolzarb.',
  },
  {
    row: 9,
    studentName: 'Dangalova Madina Amrullayevna',
    title: 'Kunjut urug‘i kunjarasidan funksional oziq-ovqat mahsulotlari ishlab chiqish',
    supervisorName: 'B.Jumayev',
    description: 'Kunjut urug‘i kunjarasini qayta ishlab, funksional oziq-ovqat mahsulotlari yaratishga qaratilgan loyiha. Oziq-ovqat xomashyosidan kompleks foydalanish va biologik qiymati yuqori mahsulotlar ishlab chiqarish bilan dolzarb.',
  },
  {
    row: 10,
    studentName: 'Tursunov Og‘abek Ikrom o‘g‘li',
    title: 'Betum va asfaltindan foydalanib asfalt yo‘llarning mustahkamligini oshirish',
    supervisorName: 'D.Shomurodov',
    description: 'Bitum va asfaltin asosida asfalt yo‘llarning mustahkamligi va xizmat muddatini oshirish texnologiyasi. Yo‘l qoplamalarining chidamliligini oshirish va mahalliy materiallardan samarali foydalanish bilan dolzarb.',
  },
  {
    row: 11,
    studentName: 'Rayimqulov Xojiakbar Gʻulomjon oʻgʻli',
    title: 'Yoqilgʻi quyish shahobchalariga onlayn navbat olish',
    supervisorName: 'B.Abdullayev',
    description: 'Yoqilg‘i quyish shoxobchalarida mijozlarga oldindan onlayn navbat olish imkonini beruvchi tizim. Kutish vaqtini kamaytirish va xizmat ko‘rsatishni raqamlashtirish bilan dolzarb.',
  },
  {
    row: 12,
    studentName: 'Yaxshilikova Zilola Baxtiyor qizi',
    title: 'Mini EduTech',
    supervisorName: 'S.O‘rinboyeva',
    description: 'Ta’lim jarayonini zamonaviy raqamli vositalar orqali tashkil etuvchi Mini EduTech platformasi. Ta’lim resurslaridan foydalanish qulayligini oshirish va raqamli o‘qitishni rivojlantirish bilan dolzarb.',
  },
  {
    row: 13,
    studentName: 'Xidirov Shokirbek Shuhrat oʻgʻli',
    title: 'Qishloq xo‘jaligi chiqindilaridan tayyorlangan substratlar asosida qo‘ziqorin yetishtirish texnologiyasini ishlab chiqish',
    supervisorName: 'E.Mamarasulov',
    description: 'Qishloq xo‘jaligi chiqindilaridan substrat tayyorlab, qo‘ziqorin yetishtirish texnologiyasini ishlab chiqishga qaratilgan. Chiqindilarni qayta ishlash, resurslardan foydalanish va oziq-ovqat ishlab chiqarishni diversifikatsiya qilish bilan dolzarb.',
  },
  {
    row: 14,
    studentName: 'Onorboyev Kamronbek Qoplonbek o‘g‘li',
    title: 'Fanlararo virtual tadqiqotlar va simulyatsiyalar platformasi',
    supervisorName: 'B.Abdullayev',
    description: 'Fanlararo virtual tadqiqotlar va simulyatsiyalarni tashkil etuvchi raqamli platforma. Turli fanlar bo‘yicha tajriba va modellashtirish imkoniyatlarini kengaytirish bilan dolzarb.',
  },
  {
    row: 15,
    studentName: 'Qarshibayeva Diyora Xusanboy qizi',
    title: 'Kelajak kimyo laboratoriyasi',
    supervisorName: 'M.Mavlonov',
    description: 'Kimyo fanini amaliy va virtual laboratoriya imkoniyatlari orqali o‘rganishga mo‘ljallangan platforma. Tajribalarni xavfsiz va interaktiv bajarish, ta’lim samaradorligini oshirish bilan dolzarb.',
  },
  {
    row: 16,
    studentName: 'Xikmatova Saida Qudratilla qizi',
    title: 'Vitofrost quruq kokteyli',
    supervisorName: 'M.Mavlonov',
    description: 'Vitofrost quruq kokteylini ishlab chiqishga qaratilgan oziq-ovqat loyihasi. Saqlashga qulay, qayta tayyorlanadigan va iste’mol uchun amaliy mahsulot yaratish ehtiyoji bilan dolzarb.',
  },
  {
    row: 17,
    studentName: 'Omanov Foziljon O‘tkir o‘g‘li',
    title: 'Gibrid havo filtri',
    supervisorName: 'I.Turdiqulov',
    description: 'Havoni filtrlash va tozalash samaradorligini oshirishga mo‘ljallangan gibrid havo filtri. Havo sifatini yaxshilash va turli sharoitlarda samarali filtrlashga bo‘lgan ehtiyoj bilan dolzarb.',
  },
  {
    row: 18,
    studentName: 'Abduvaliyeva Hilola Rahim qizi',
    title: 'Retwins',
    supervisorName: 'M.Mavlonov',
    description: 'Retwins loyihasi asosida innovatsion mahsulot yoki xizmatni ishlab chiqish va amaliyotga joriy etishga qaratilgan. Yangi yechimlarni tijoratlashtirish va innovatsion faoliyatni rivojlantirish bilan dolzarb.',
  },
  {
    row: 19,
    studentName: 'Toirov Roʻzimat Maxmud oʻgʻli',
    title: 'Remote hazard detection devise (Rhd²)',
    supervisorName: 'U.Turdiyev',
    description: 'Masofadan xavfni aniqlash qurilmasi bo‘lib, xavfli holatlarni masofadan kuzatish va aniqlashga yo‘naltirilgan. Xavfsizlikni oshirish va xavfli vaziyatlarga tezkor munosabat bildirish bilan dolzarb.',
  },
  {
    row: 20,
    studentName: 'Samidli Jalaladdin Mushviq og‘lu',
    title: 'O‘quvchilar uchun testlarni oddiy usulda emas, balki o‘yin shaklida yechishga mo‘ljallangan raqamli platforma',
    supervisorName: 'B.Abdullayev',
    description: 'O‘quvchilar testlarini o‘yin elementlari asosida bajarishga mo‘ljallangan raqamli platforma. Ta’limga qiziqishni oshirish, bilimni interaktiv baholash va o‘quv jarayonini zamonaviylashtirish bilan dolzarb.',
  },
  {
    row: 21,
    studentName: 'Tursunboyev Abdulvohid Azimjon o‘g‘li',
    title: 'Eco parda',
    supervisorName: 'D.Bobonov',
    description: 'Ekologik materiallardan parda ishlab chiqarishga qaratilgan loyiha. Atrof-muhitga zararini kamaytiruvchi mahsulotlardan foydalanish va ekologik yo‘nalishdagi ishlab chiqarishni rivojlantirish bilan dolzarb.',
  },
  {
    row: 22,
    studentName: 'Xolmominov Shodiyor Jaloliddin o‘g‘li',
    title: 'Talabalar turar joy platformasi-bu talabalar uchun moʻljallangan raqamli platformasi',
    supervisorName: 'B.Abdullayev',
    description: 'Talabalar turar joyini boshqarish, axborot almashish va talabalar uchun xizmatlarni raqamlashtirishga mo‘ljallangan platforma. TTJ boshqaruvini soddalashtirish va talabalar uchun qulaylik yaratish bilan dolzarb.',
  },
  {
    row: 23,
    studentName: 'Bobojonov Hayotbek Abdukarim o‘g‘li',
    title: 'Quyosh panellari',
    supervisorName: 'A.Norboyev',
    description: 'Quyosh energiyasidan foydalanib elektr energiyasi ishlab chiqarishga mo‘ljallangan tizim. Qayta tiklanuvchi energiyadan foydalanish va energiya tejamkorligini oshirish bilan dolzarb.',
  },
  {
    row: 24,
    studentName: 'Xamraqulova Gulsevar Xazratqul qizi',
    title: 'Qandak',
    supervisorName: 'M.Mavlonov',
    description: 'Qandak asosida innovatsion mahsulot yaratishga qaratilgan oziq-ovqat loyihasi. Mahalliy xomashyodan samarali foydalanish va yangi turdagi mahsulotlarni ishlab chiqarish bilan dolzarb.',
  },
  {
    row: 25,
    studentName: 'Toʻraqulov Ahadbek Neʼmatjon oʻgʻli',
    title: 'Isteʼmolchilarni himoyalash',
    supervisorName: 'U.Turdiyev',
    description: 'Iste’molchilar huquqlarini himoyalash va ularning murojaatlarini qo‘llab-quvvatlashga qaratilgan loyiha. Iste’molchilar manfaatlarini himoya qilish va xizmatlardan foydalanish jarayonini yaxshilash bilan dolzarb.',
  },
  {
    row: 26,
    studentName: 'Nasridenov Quvonchbek Tuxtamurod o’g’li',
    title: 'Shamol parrak',
    supervisorName: 'U.Turdiyev',
    description: 'Shamol energiyasidan foydalanishga mo‘ljallangan shamol parrak qurilmasi. Qayta tiklanuvchi energiya manbalaridan foydalanish va energiya samaradorligini oshirish bilan dolzarb.',
  },
  {
    row: 27,
    studentName: 'Gʻaniyev Komiljon Yorqinovich',
    title: 'Elektr energiya',
    supervisorName: 'S.Abdurahmonova',
    description: 'Elektr energiyasidan samarali foydalanish va energiya ta’minotiga oid yechimlarni ishlab chiqishga qaratilgan loyiha. Energiya tejamkorligi va barqaror elektr ta’minotini rivojlantirish bilan dolzarb.',
  },
  {
    row: 28,
    studentName: 'Nabiyev Sardorbek Iqboljon oʻgʻli',
    title: 'Tabiiy kompanetlardan foydalanib guletensiz non va makron mahsulotlarni ishlab chiqarish',
    supervisorName: 'F.Rahmatov',
    description: 'Tabiiy komponentlar asosida glyutensiz non va makaron mahsulotlari ishlab chiqarishga qaratilgan. Maxsus ovqatlanish ehtiyojlariga mos mahsulotlar assortimentini kengaytirish bilan dolzarb.',
  },
  {
    row: 29,
    studentName: 'To‘rayev Dilshod Shuhrat o‘g‘li',
    title: 'Havsiz elektromabil quvvatlsh stansiyasi',
    supervisorName: 'Sh.Utkirov',
    description: 'Elektr transport vositalarini quvvatlash uchun xavfsiz elektromobil quvvatlash stansiyasini yaratishga qaratilgan. Elektromobillardan foydalanishni qo‘llab-quvvatlash va quvvatlash infratuzilmasini rivojlantirish bilan dolzarb.',
  },
  {
    row: 30,
    studentName: 'Shamsiddinov Rustambek Gʻaybulla oʻgʻli',
    title: 'Ekologik toza havo bilan nafas olish boʻyicha',
    supervisorName: 'S.Abdurahmonova',
    description: 'Toza havo bilan nafas olish sharoitini yaxshilashga qaratilgan ekologik loyiha. Havo sifatini yaxshilash va insonlar uchun qulay ekologik muhit yaratish bilan dolzarb.',
  },
  {
    row: 31,
    studentName: 'Inadullayev Javohir Ilyos o‘g‘li',
    title: 'Eco loyha',
    supervisorName: 'B.Jumayev',
    description: 'Ekologik yo‘nalishdagi loyiha bo‘lib, atrof-muhitga salbiy ta’sirni kamaytiruvchi yechim yaratishga qaratilgan. Chiqindilarni kamaytirish va ekologik barqarorlikni ta’minlash bilan dolzarb.',
  },
  {
    row: 32,
    studentName: 'Yo‘ldosheva Madina Ahmad qizi',
    title: 'Pomidor urug\'idan yo\'g ishlab chiqarish',
    supervisorName: 'M.Mavlonov',
    description: 'Pomidor urug‘idan yog‘ ishlab chiqarish texnologiyasini ishlab chiqishga qaratilgan. Qishloq xo‘jaligi xomashyosidan kompleks foydalanish va qo‘shimcha qiymatli mahsulot olish bilan dolzarb.',
  },
  {
    row: 33,
    studentName: 'Madusmonova Zilola Abdunazar qizi',
    title: 'Kanakunjut urugʻini kompleks qayta ishlash',
    supervisorName: 'M.Mavlonov',
    description: 'Kanakunjut urug‘ini kompleks qayta ishlash orqali bir nechta foydali mahsulotlar olishga qaratilgan. Xomashyodan to‘liq foydalanish va chiqindilarni kamaytirish bilan dolzarb.',
  },
  {
    row: 34,
    studentName: 'Umaraliyev Azizbek Akram oʻgʻli',
    title: 'Ultrabinafsha nuri orqali suv va sharbatlarni muddatini uzaytirish',
    supervisorName: 'B.Jumayev',
    description: 'Ultrabinafsha nurlanish yordamida suv va sharbatlarning saqlanish muddatini uzaytirishga qaratilgan texnologiya. Mahsulot xavfsizligi va saqlash barqarorligini oshirish bilan dolzarb.',
  },
  {
    row: 35,
    studentName: 'Anvarov Jasurbek Jamshidbek oʻgʻli',
    title: 'Sabzavotlar yordamida turli-xil rangdagi tabiy makaron ishlab chiqarish',
    supervisorName: 'F.Rahmatov',
    description: 'Sabzavotlardan tabiiy rang beruvchi komponentlar foydalanib, turli rangdagi makaron ishlab chiqarish texnologiyasi. Sun’iy rang beruvchilarga muqobil tabiiy mahsulot yaratish bilan dolzarb.',
  },
  {
    row: 36,
    studentName: 'Baxtiyorova Muxlisa Poʻlat qizi',
    title: 'Chirituvchi bakteriyalar',
    supervisorName: 'M.Mavlonov',
    description: 'Chirituvchi bakteriyalarning xususiyatlarini o‘rganish va ulardan amaliy maqsadlarda foydalanishga qaratilgan loyiha. Biotexnologik jarayonlarni rivojlantirish va mikroorganizmlardan samarali foydalanish bilan dolzarb.',
  },
  {
    row: 37,
    studentName: 'Abdikaxarova Madina Axmad qizi',
    title: 'Ekologik tuvaklar',
    supervisorName: 'M.Mavlonov',
    description: 'Ekologik materiallardan tuvaklar ishlab chiqarishga qaratilgan loyiha. Plastik va boshqa an’anaviy materiallarga ekologik muqobillarni rivojlantirish bilan dolzarb.',
  },
  {
    row: 38,
    studentName: 'Toʻraboyev Iskandar Baxtiyor oʻgʻli',
    title: 'Ishlab chiqarishdagi CO2 gazini qayta ishlash',
    supervisorName: 'A.Eminov',
    description: 'Ishlab chiqarishda hosil bo‘ladigan CO2 gazini qayta ishlash va undan foydali yo‘nalishda foydalanishga qaratilgan. Issiqxona gazlari chiqindilarini kamaytirish va resurslarni qayta ishlatish bilan dolzarb.',
  },
  {
    row: 39,
    studentName: 'Rahmonova Laylo Abbos qizi',
    title: 'Xavfsiz uy',
    supervisorName: 'S.Abdurahmonova',
    description: 'Uy xavfsizligini monitoring qilish va xavfli holatlarni aniqlashga mo‘ljallangan tizim. Xonadonlarda xavfsizlikni oshirish va zamonaviy monitoring vositalaridan foydalanish bilan dolzarb.',
  },
  {
    row: 40,
    studentName: 'Xamraqulova Gulsevar Xazratqul qizi',
    title: 'Shokoladli oʻrik',
    supervisorName: 'M.Mavlonov',
    description: 'O‘rik asosida shokoladli oziq-ovqat mahsuloti yaratishga qaratilgan. Mahalliy mevalarni qayta ishlash va yangi turdagi iste’mol mahsulotlarini ishlab chiqarish bilan dolzarb.',
  },
  {
    row: 41,
    studentName: 'Abdumalikov Dilshod Ravshan o‘g‘li',
    title: 'Mazutli chiqindidan nodir metallar ajratib olish',
    supervisorName: 'S.Abdurahmonova',
    description: 'Mazutli chiqindilardan nodir metallarni ajratib olish texnologiyasini ishlab chiqishga qaratilgan. Sanoat chiqindilarini qayta ishlash va qimmatli komponentlarni qayta tiklash bilan dolzarb.',
  },
  {
    row: 42,
    studentName: 'Burxonov Akmaljon Xamidovich',
    title: 'Mahalliy hom ashyodan qurt ishlab chiqarish va uch ishchi organli qurilma loyhalash',
    supervisorName: 'M.Mavlonov',
    description: 'Mahalliy xomashyodan qurt ishlab chiqarish va uch ishchi organli qurilmani loyihalashga qaratilgan. Milliy oziq-ovqat mahsulotini zamonaviy texnologiya asosida ishlab chiqarish va mexanizatsiyalash bilan dolzarb.',
  },
  {
    row: 43,
    studentName: 'Qarshibayeva Diyora Xusanboy qizi',
    title: 'Kelajak kimyo laboratoriyasi (Raqamli platforma)',
    supervisorName: 'M.Mavlonov',
    description: 'Kimyo fanini zamonaviy laboratoriya va raqamli vositalar yordamida o‘rganishga qaratilgan platforma. Amaliy tajribalarni qulay va xavfsiz tashkil etish bilan dolzarb.',
  },
  {
    row: 44,
    studentName: 'Abdunabiyeva Habiba Alisher qizi',
    title: 'Zakaz somsa bot',
    supervisorName: 'M.Mavlonov',
    description: 'Zakaz somsa bot orqali somsa buyurtmalarini qabul qilish va xizmat jarayonini avtomatlashtirishga qaratilgan. Buyurtmalarni tezkor qabul qilish va mijozlarga xizmat ko‘rsatishni raqamlashtirish bilan dolzarb.',
  },
  {
    row: 45,
    studentName: 'Quvanova Rahima Sobirjon qizi',
    title: 'Undirilgan mosh- vitaminga boy ozuqa',
    supervisorName: 'M.Sobirova',
    description: 'Moshni undirib, vitaminlarga boy ozuqa olishga qaratilgan loyiha. Oziqaviy qiymati yuqori mahsulotlar yaratish va mahalliy xomashyodan samarali foydalanish bilan dolzarb.',
  },
  {
    row: 46,
    studentName: 'Nurmetov Hayot Baxodir o‘g‘li',
    title: '3 fazali motorni 1 fazali elektr tarmog\'iga ulash',
    supervisorName: 'D.Bobonov',
    description: 'Uch fazali motorni bir fazali elektr tarmog‘iga ulash imkonini beruvchi texnik yechim. Mavjud elektr tarmoqlaridan samarali foydalanish va elektr qurilmalarini moslashtirish bilan dolzarb.',
  },
  {
    row: 47,
    studentName: 'Jarkinboyeva Zuhra Sharofiddin qizi',
    title: 'Litiy temir fosfat (LiFe PO4) katod materialli chiqindi litiy ion batarekalarini chuqur qayta ishlash orqali litiy birikmalarini ajratib olish texnologiyalari',
    supervisorName: 'D.Shodmonqulov',
    description: 'Chiqindi litiy-ion batareyalarini chuqur qayta ishlab, litiy birikmalarini ajratib olish texnologiyasi. Batareya chiqindilarini kamaytirish va qimmatli materiallarni qayta tiklash bilan dolzarb.',
  },
  {
    row: 48,
    studentName: 'Abduxakimov Ozodbek Ashraf o‘g‘li',
    title: 'Shes',
    supervisorName: 'Sh.Utkirov',
    description: 'ShES loyihasi bo‘lib, shamol energetikasidan foydalanishga qaratilgan texnik yechim. Qayta tiklanuvchi energiya manbalarini rivojlantirish va energiya samaradorligini oshirish bilan dolzarb.',
  },
  {
    row: 49,
    studentName: 'Toʻrayeva Marjona Yoʻlchi qizi',
    title: 'Iqlim va ob-havo sharoitiga moslashgan kiyim tanlash avtomatlashtirilgan tizimi platformasi',
    supervisorName: 'B.Abdullayev',
    description: 'Iqlim va ob-havo sharoitiga mos kiyim tanlashni avtomatlashtiruvchi platforma. Foydalanuvchiga sharoitga mos kiyim tanlashda yordam berish va raqamli xizmatlarni rivojlantirish bilan dolzarb.',
  },
  {
    row: 50,
    studentName: 'Saydullayev Asadbek Xayrulla oʻgʻli',
    title: 'UniWorld – ta’lim xizmatlari va axborot resurslarini birlashtiruvchi raqamli platformasi',
    supervisorName: 'B.Abdullayev',
    description: 'Ta’lim xizmatlari va axborot resurslarini yagona raqamli platformada birlashtirishga qaratilgan. Ta’lim resurslariga kirishni soddalashtirish va xizmatlarni markazlashtirish bilan dolzarb.',
  },
  {
    row: 51,
    studentName: 'Karimova Gulnora Raxmatula qizi',
    title: 'Talabaning ijtimoiy faolligini aniqlovchi raqamli platforma',
    supervisorName: 'B.Abdullayev',
    description: 'Talabaning ijtimoiy faolligini raqamli ko‘rsatkichlar asosida aniqlashga mo‘ljallangan platforma. Talabalar faolligini tizimli monitoring qilish va rivojlanishni qo‘llab-quvvatlash bilan dolzarb.',
  },
  {
    row: 52,
    studentName: 'Tuxtaboyev Ibroxim Muhiddin o‘g‘li',
    title: 'Fizika fani labaratoriyasini simulyatsiyalash (Virtual laboratoriya)',
    supervisorName: 'B.Abdullayev',
    description: 'Fizika laboratoriyalarini virtual muhitda simulyatsiya qilishga mo‘ljallangan yechim. Amaliy tajribalarni raqamli shaklda bajarish va ta’lim imkoniyatlarini kengaytirish bilan dolzarb.',
  },
  {
    row: 53,
    studentName: 'Qarshiboyev Shahboz Aktam oʻgʻli',
    title: 'Sirdaryo viloyati Davlat xizmatlarini professional darajada o’rgatish platformasi',
    supervisorName: 'B.Abdullayev',
    description: 'Sirdaryo viloyati davlat xizmatlarini professional darajada o‘rgatishga mo‘ljallangan ta’lim platformasi. Davlat xizmatlari bo‘yicha bilim va amaliy ko‘nikmalarni rivojlantirish bilan dolzarb.',
  },
  {
    row: 54,
    studentName: 'Xolmurodov Ogʻabek Toshbolta oʻgʻli',
    title: 'Lazer quriqchi',
    supervisorName: 'A.Norboyev',
    description: 'Lazer yordamida quritish jarayonini amalga oshirishga qaratilgan texnologik yechim. Quritish jarayonini takomillashtirish va energiya hamda vaqt sarfini optimallashtirish bilan dolzarb.',
  },
  {
    row: 55,
    studentName: 'Nazarov Javohir Ro‘zimurod o‘g‘li',
    title: 'TaxFlow AI loyihasi',
    supervisorName: 'N.Azamqulov',
    description: 'TaxFlow AI soliq va moliyaviy jarayonlarni sun’iy intellekt asosida avtomatlashtirishga yo‘naltirilgan loyiha. Hisob-kitoblarni soddalashtirish va raqamli xizmatlardan foydalanishni kengaytirish bilan dolzarb.',
  },
  {
    row: 56,
    studentName: 'Suyunov Begzodjon',
    title: 'Zamonaviy inergiya tejamkor saqlash omborlarini urush texnalogiyasi',
    supervisorName: 'U.Bababekov',
    description: 'Zamonaviy energiya tejamkor saqlash omborlarini yaratish texnologiyasiga qaratilgan. Mahsulotlarni saqlashda energiya sarfini kamaytirish va saqlash samaradorligini oshirish bilan dolzarb.',
  },
  {
    row: 57,
    studentName: 'Berdiqulov Sunnat Inomjonvich',
    title: 'Issiqxonalarda qulpnay yetishtirishni takomillashtirish texnalogiyasi',
    supervisorName: 'U.Bababekov',
    description: 'Issiqxonalarda qulupnay yetishtirish texnologiyasini takomillashtirishga qaratilgan. Yopiq sharoitda hosildorlikni oshirish va zamonaviy agrotexnologiyalarni qo‘llash bilan dolzarb.',
  },
  {
    row: 58,
    studentName: 'Onorboyev Kamronbek Qoplonbek o‘g‘li',
    title: 'SmartEduLab',
    supervisorName: 'B.Abdullayev',
    description: 'SmartEduLab ta’lim jarayonlarini raqamlashtirish, tajriba va o‘quv faoliyatini zamonaviy vositalar bilan tashkil etishga qaratilgan. Ta’lim sifatini oshirish va raqamli laboratoriya imkoniyatlarini kengaytirish bilan dolzarb.',
  },
  {
    row: 59,
    studentName: 'Sobirov Asror Ismatulla oʻgʻli',
    title: 'Havodan Suv olish Asosida Avtomatlashtirilgan sugʻorish tizimi',
    supervisorName: 'D.Bobonov',
    description: 'Havodan suv olish asosida avtomatlashtirilgan sug‘orish tizimini yaratishga qaratilgan. Suv tanqisligi sharoitida suv resurslaridan samarali foydalanish va sug‘orishni avtomatlashtirish bilan dolzarb.',
  },
  {
    row: 60,
    studentName: 'Xikmatova Saida Qudratilla qizi',
    title: 'Vitofrost',
    supervisorName: 'M.Mavlonov',
    description: 'Vitofrost quruq mahsulotini ishlab chiqish va qulay saqlash shaklini yaratishga qaratilgan. Mahsulotning saqlanishi va foydalanish qulayligini oshirish bilan dolzarb.',
  },
  {
    row: 61,
    studentName: 'Sattiyev Saidabbos Azizillo oʻgʻli',
    title: 'Suv yordamida quyosh panellarini tozalash',
    supervisorName: 'A.Norboyev',
    description: 'Quyosh panellarini suv yordamida tozalash jarayonini avtomatlashtirishga qaratilgan. Panellarning samaradorligini saqlash va texnik xizmat ko‘rsatishni yengillashtirish bilan dolzarb.',
  },
  {
    row: 62,
    studentName: 'Mirsharaf Xolmuminov Orif oʻgʻli',
    title: '3d printer xomashyosi ishlab chiqarish',
    supervisorName: 'B.Abdullayev',
    description: '3D printer uchun xomashyo ishlab chiqarishga qaratilgan loyiha. Mahalliy xomashyo asosida 3D bosib chiqarish materiallarini ishlab chiqarish va texnologik mustaqillikni oshirish bilan dolzarb.',
  },
  {
    row: 63,
    studentName: 'Rahmonova Laylo Abbos qizi',
    title: 'smart dustbin',
    supervisorName: 'S.Abdurahmonova',
    description: 'Smart Dustbin — chiqindilarni zamonaviy usulda yig‘ish va boshqarishga qaratilgan aqlli chiqindi qutisi. Chiqindilarni boshqarish samaradorligini oshirish va ekologik muhitni yaxshilash bilan dolzarb.',
  },
  {
    row: 64,
    studentName: 'Omonboyev Nodir Akmal oʻgʻli',
    title: 'Subli fruit',
    supervisorName: 'M.Mavlonov',
    description: 'Mevalarni sublimatsion quritish asosida uzoq muddat saqlanadigan mahsulot olishga qaratilgan. Mevalarning ozuqaviy qiymatini saqlash va saqlash muddatini uzaytirish bilan dolzarb.',
  },
  {
    row: 65,
    studentName: 'Korabekova Gulnoza Shuxrat qizi',
    title: 'EcoFresh Cabbage Indicator',
    supervisorName: 'S.Abdurahmonova',
    description: 'EcoFresh Cabbage Indicator karamning yangiligi va saqlanish holatini indikator orqali aniqlashga qaratilgan. Oziq-ovqat mahsulotlari sifatini nazorat qilish va isrofgarchilikni kamaytirish bilan dolzarb.',
  },
  {
    row: 66,
    studentName: 'Nomonjonova Zaxro Farhodjon qizi',
    title: 'Universitet arxiv portalini yaratishga qaratilgan veb-ilova platformasi',
    supervisorName: 'B.Abdullayev',
    description: 'Universitet arxivini boshqarish va hujjatlarga raqamli kirishni ta’minlovchi veb-ilova. Arxiv ma’lumotlarini tizimlashtirish, qidirish va saqlash jarayonini raqamlashtirish bilan dolzarb.',
  },
  {
    row: 67,
    studentName: 'Mirahmatov Farrux Farhod oʻgʻli',
    title: 'Rus tilini raqamlashtirish platformasi',
    supervisorName: 'B.Abdullayev',
    description: 'Rus tilini raqamli vositalar orqali o‘rganish va o‘qitishga mo‘ljallangan platforma. Til ta’limini interaktivlashtirish va o‘quv resurslaridan foydalanishni kengaytirish bilan dolzarb.',
  },
  {
    row: 68,
    studentName: 'Qochqaorova Aziza Zokir qizi',
    title: 'Eko o‘g‘it',
    supervisorName: 'M.Nosirov',
    description: 'Eko o‘g‘it ishlab chiqarishga qaratilgan loyiha. Qishloq xo‘jaligida ekologik va samarali o‘g‘itlardan foydalanish hamda tuproq unumdorligini qo‘llab-quvvatlash bilan dolzarb.',
  },
  {
    row: 69,
    studentName: 'Sherzotov Nazarbek Sherzod oʻgʻli',
    title: 'O’quv markazni boshqarish tizimi platformasi',
    supervisorName: 'B.Abdullayev',
    description: 'O‘quv markazini boshqarish, o‘quvchilar va ta’lim jarayonini raqamlashtirishga mo‘ljallangan platforma. Boshqaruvni soddalashtirish va ta’lim xizmatlari samaradorligini oshirish bilan dolzarb.',
  },
  {
    row: 70,
    studentName: 'Kamoliddinov Muhiddin G‘aybiddin oʻgʻli',
    title: 'O’qituvchilar va talabalar uchun qulay test yaratish va test ishlash platformasi',
    supervisorName: 'B.Abdullayev',
    description: 'O‘qituvchilar va talabalar uchun test yaratish, tarqatish va ishlash imkonini beruvchi platforma. Bilimni tezkor baholash va test jarayonini raqamlashtirish bilan dolzarb.',
  },
  {
    row: 71,
    studentName: 'Qurbonboyeva Maftuna Sapar qizi',
    title: 'Aqilli isiqxona',
    supervisorName: 'A.Sangirov',
    description: 'Aqlli issiqxona harorat, namlik va boshqa sharoitlarni monitoring qilish hamda boshqarishga qaratilgan. Resurslarni tejash va issiqxona hosildorligini oshirish bilan dolzarb.',
  },
  {
    row: 72,
    studentName: 'Maxmanazarov Sardor Toirjon o‘g‘li',
    title: 'Elektr energiyasz vakum orqali ishlaydigan quduqdan suv chiqarish qurilmasi',
    supervisorName: 'A.Sangirov',
    description: 'Elektr energiyasidan foydalanmasdan vakuum orqali quduqdan suv chiqarishga mo‘ljallangan qurilma. Suv chiqarish jarayonida energiya sarfini kamaytirish va muqobil texnik yechim yaratish bilan dolzarb.',
  },
  {
    row: 73,
    studentName: 'Xolyigitov Abbos G‘anisher o‘g‘li',
    title: 'Aqilli turargoh',
    supervisorName: 'A.Sangirov',
    description: 'Aqlli turargoh transport vositalarini joylashtirish va turargohdan foydalanishni raqamli boshqarishga qaratilgan. Shahar infratuzilmasidan samarali foydalanish va haydovchilar uchun qulaylik yaratish bilan dolzarb.',
  },
  {
    row: 74,
    studentName: 'Omonqulov Asadbek Asqar o‘g‘li',
    title: 'Elektro mobil',
    supervisorName: 'Sh.Utkirov',
    description: 'Elektromobil yaratish va undan foydalanish imkoniyatlarini rivojlantirishga qaratilgan loyiha. Ekologik toza transport vositalarini kengaytirish va yoqilg‘i sarfini kamaytirish bilan dolzarb.',
  },
  {
    row: 75,
    studentName: 'Alisherova Gulbaxor Alisher qizi',
    title: 'Temiryo’lni avtomatlashtirish',
    supervisorName: 'A.Sangirov',
    description: 'Temiryo‘l tizimlarini avtomatlashtirish va boshqaruv jarayonlarini takomillashtirishga qaratilgan. Transport xavfsizligi, boshqaruv samaradorligi va raqamlashtirishni oshirish bilan dolzarb.',
  },
  {
    row: 76,
    studentName: 'Muhiddinov Muhriddin Zuhriddin oʻgʻli',
    title: 'Sirdaryo viloyatining raqamli bozori platformasi',
    supervisorName: 'B.Abdullayev',
    description: 'Sirdaryo viloyatidagi savdo va xizmatlarni raqamli muhitda birlashtiruvchi bozor platformasi. Mahalliy tadbirkorlar va iste’molchilar o‘rtasidagi raqamli aloqani rivojlantirish bilan dolzarb.',
  },
  {
    row: 77,
    studentName: 'Jalilov Zayniddin Shuhrat oʻgʻli',
    title: 'Investor',
    supervisorName: 'M.Nosirov',
    description: 'Investorlarni loyihalar va investitsiya imkoniyatlari bilan bog‘lashga qaratilgan raqamli yechim. Innovatsion loyihalarni moliyalashtirish imkoniyatlarini kengaytirish va investorlar bilan aloqani soddalashtirish bilan dolzarb.',
  },
  {
    row: 78,
    studentName: 'Inadullayev Javohir Ilyos o‘g‘li',
    title: 'Asalarichilikni rivojlantirish',
    supervisorName: 'M.Sobirova',
    description: 'Asalarichilikni rivojlantirish, mahsuldorlikni oshirish va zamonaviy usullarni qo‘llashga qaratilgan loyiha. Asalarichilik mahsulotlarini ko‘paytirish va tarmoq samaradorligini oshirish bilan dolzarb.',
  },
];
