export interface RawDocStudent {
  row: number;
  fullName: string;
  group: string;
  courseStr: string;
  course: number;
  phone: string;
  supervisorName: string;
  facultyOrField: string;
}

export interface SupervisorSeedData {
  shortName: string;
  fullName: string;
  position: string;
  academicDegree: string;
  department: string;
  phone: string;
  email: string;
  aliases: string[];
}

export const SUPERVISORS_SEED_LIST: SupervisorSeedData[] = [
  {
    shortName: 'B.Jumayev',
    fullName: 'Baxtiyor Jumayev',
    position: 'Dotsent',
    academicDegree: 'PhD',
    department: 'Axborot texnologiyalari',
    phone: '+998901234511',
    email: 'b.jumayev@yangiyer-tkti.uz',
    aliases: ['b.jumayev', 'jumayev b', 'b.jumayev ', 'baxtiyor jumayev', 'jumayev'],
  },
  {
    shortName: 'B.Abdullayev',
    fullName: 'Baxtiyor Abdullayev',
    position: 'Dotsent',
    academicDegree: 'PhD',
    department: 'Axborot texnologiyalari',
    phone: '+998901234512',
    email: 'b.abdullayev@yangiyer-tkti.uz',
    aliases: ['b.abdullayev', 'abdullayev b', 'baxtiyor abdullayev', 'abdullayev'],
  },
  {
    shortName: 'D.Shomurodov',
    fullName: 'Dilshod Shomurodov',
    position: 'Katta o‘qituvchi',
    academicDegree: 'PhD',
    department: 'Iqtisodiyot va menejment',
    phone: '+998901234513',
    email: 'd.shomurodov@yangiyer-tkti.uz',
    aliases: ['d.shomurodov', 'shomurodov d', 'dilshod shomurodov', 'shomurodov'],
  },
  {
    shortName: 'S.O‘rinboyeva',
    fullName: 'Sanobar O‘rinboyeva',
    position: 'Dotsent',
    academicDegree: 'PhD',
    department: 'Oziq-ovqat va biotexnologiya',
    phone: '+998901234514',
    email: 's.orinboyeva@yangiyer-tkti.uz',
    aliases: ['s.o‘rinboyeva', 's.o\'rinboyeva', 'o‘rinboyeva s', 'o\'rinboyeva s', 'sanobar o‘rinboyeva'],
  },
  {
    shortName: 'E.Mamarasulov',
    fullName: 'Erkin Mamarasulov',
    position: 'Katta o‘qituvchi',
    academicDegree: 'PhD',
    department: 'Texnologik mashinalar va jihozlar',
    phone: '+998901234515',
    email: 'e.mamarasulov@yangiyer-tkti.uz',
    aliases: ['e.mamarasulov', 'mamarasulov e', 'erkin mamarasulov', 'mamarasulov'],
  },
  {
    shortName: 'M.Mavlonov',
    fullName: 'Mansur Mavlonov',
    position: 'Katta o‘qituvchi',
    academicDegree: 'PhD',
    department: 'Oziq-ovqat va biotexnologiya',
    phone: '+998901234501',
    email: 'm.mavlonov@edu.uz',
    aliases: ['m.mavlonov', 'mavlonov m', 'mansur mavlonov', 'mavlonov'],
  },
  {
    shortName: 'I.Turdiqulov',
    fullName: 'Ilhom Turdiqulov',
    position: 'Dotsent',
    academicDegree: 'PhD',
    department: 'Iqtisodiyot va menejment',
    phone: '+998901234516',
    email: 'i.turdiqulov@yangiyer-tkti.uz',
    aliases: ['i.turdiqulov', 'turdiqulov i', 'ilhom turdiqulov', 'turdiqulov'],
  },
  {
    shortName: 'U.Turdiyev',
    fullName: 'Ulug‘bek Turdiyev',
    position: 'Dotsent',
    academicDegree: 'PhD',
    department: 'Avtomatlashtirish va boshqaruv',
    phone: '+998901234517',
    email: 'u.turdiyev@yangiyer-tkti.uz',
    aliases: ['u.turdiyev', 'turdiyev u', 'ulug‘bek turdiyev', 'ulugbek turdiyev', 'turdiyev'],
  },
  {
    shortName: 'D.Bobonov',
    fullName: 'Dilmurod Bobonov',
    position: 'Dotsent',
    academicDegree: 'PhD',
    department: 'Avtomatlashtirish va boshqaruv',
    phone: '+998901234518',
    email: 'd.bobonov@yangiyer-tkti.uz',
    aliases: ['d.bobonov', 'bobonov d', 'dilmurod bobonov', 'bobonov'],
  },
  {
    shortName: 'A.Norboyev',
    fullName: 'Abduaxad Norboyev',
    position: 'Dotsent',
    academicDegree: 'PhD',
    department: 'Mashinasozlik va mexanika',
    phone: '+998901234506',
    email: 'a.norboyev@edu.uz',
    aliases: ['a.norboyev', 'norboyev a', 'abduaxad norboyev', 'norboyev'],
  },
  {
    shortName: 'S.Abdurahmonova',
    fullName: 'Saida Abdurahmonova',
    position: 'Dotsent',
    academicDegree: 'PhD',
    department: 'Avtomatlashtirish va boshqaruv',
    phone: '+998901234519',
    email: 's.abdurahmonova@yangiyer-tkti.uz',
    aliases: ['s.abdurahmonova', 'abdurahmonova s', 'saida abdurahmonova', 'abdurahmonova'],
  },
  {
    shortName: 'F.Rahmatov',
    fullName: 'Farhod Rahmatov',
    position: 'Dotsent',
    academicDegree: 'PhD',
    department: 'Texnologik mashinalar va jihozlar',
    phone: '+998901234520',
    email: 'f.rahmatov@yangiyer-tkti.uz',
    aliases: ['f.rahmatov', 'f.raxmatov', 'rahmatov f', 'raxmatov f', 'farhod rahmatov', 'farxod raxmatov'],
  },
  {
    shortName: 'Sh.Utkirov',
    fullName: 'Shuhrat O‘tkirov',
    position: 'Dotsent',
    academicDegree: 'PhD',
    department: 'Dasturiy injiniring va sun’iy intellekt',
    phone: '+998901234521',
    email: 'sh.utkirov@yangiyer-tkti.uz',
    aliases: ['sh.utkirov', 'utkirov sh', 'shuhrat o‘tkirov', 'shuhrat utkirov', 'utkirov'],
  },
  {
    shortName: 'A.Eminov',
    fullName: 'Anvar Eminov',
    position: 'Dotsent',
    academicDegree: 'PhD',
    department: 'Kimyo muhandisligi',
    phone: '+998901234522',
    email: 'a.eminov@yangiyer-tkti.uz',
    aliases: ['a.eminov', 'eminov a', 'anvar eminov', 'eminov'],
  },
  {
    shortName: 'M.Sobirova',
    fullName: 'Mohichehra Sobirova',
    position: 'Katta o‘qituvchi',
    academicDegree: 'PhD',
    department: 'Oziq-ovqat texnologiyasi',
    phone: '+998901234505',
    email: 'm.sobirova@edu.uz',
    aliases: ['m.sobirova', 'sobirova m', 'mohichehra sobirova', 'sobirova'],
  },
  {
    shortName: 'D.Shodmonqulov',
    fullName: 'Doston Shodmonqulov',
    position: 'Katta o‘qituvchi',
    academicDegree: 'PhD',
    department: 'Iqtisodiyot va menejment',
    phone: '+998901234523',
    email: 'd.shodmonqulov@yangiyer-tkti.uz',
    aliases: ['d.shodmonqulov', 'shodmonqulov d', 'doston shodmonqulov', 'shodmonqulov'],
  },
  {
    shortName: 'N.Azamqulov',
    fullName: 'Nodirbek A’zamqulov',
    position: 'Katta o‘qituvchi',
    academicDegree: 'PhD',
    department: 'Ishlab chiqarish jarayonlarini avtomatlashtirish',
    phone: '+998901234524',
    email: 'n.azamqulov@yangiyer-tkti.uz',
    aliases: ['n.azamqulov', 'azamqulov n', 'nodirbek a’zamqulov', 'nodirbek azamqulov', 'azamqulov'],
  },
  {
    shortName: 'U.Bababekov',
    fullName: 'Ulug‘bek Bobobekov',
    position: 'Dotsent',
    academicDegree: 'PhD',
    department: 'Oziq-ovqat va biotexnologiya',
    phone: '+998901234525',
    email: 'u.bababekov@yangiyer-tkti.uz',
    aliases: ['u.bababekov', 'bababekov u', 'ulug‘bek bobobekov', 'ulugbek bababekov', 'bobobekov', 'bababekov'],
  },
  {
    shortName: 'M.Nosirov',
    fullName: 'Muzaffar Nosirov',
    position: 'Dotsent',
    academicDegree: 'PhD',
    department: 'Mashinasozlik va mexanika',
    phone: '+998901234526',
    email: 'm.nosirov@yangiyer-tkti.uz',
    aliases: ['m.nosirov', 'nosirov m', 'muzaffar nosirov', 'nosirov'],
  },
  {
    shortName: 'A.Sangirov',
    fullName: 'Abdumajid Sangirov',
    position: 'Dotsent',
    academicDegree: 'PhD',
    department: 'Texnologik mashina va uskunalar',
    phone: '+998901234527',
    email: 'a.sangirov@yangiyer-tkti.uz',
    aliases: ['a.sangirov', 'sangirov a', 'abdumajid sangirov', 'sangirov'],
  },
];

export const OFFICIAL_STUDENTS_LIST: RawDocStudent[] = [
  {
    row: 1,
    fullName: 'Muzaffarov Sarvar Sanjar o‘g‘li',
    group: 'M301-24',
    courseStr: '2-kurs (magistratura)',
    course: 2,
    phone: '+998900010001',
    supervisorName: 'B.Jumayev',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 2,
    fullName: 'Ernazarova Malika Erkin qizi',
    group: '11-01-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998932717704',
    supervisorName: 'B.Abdullayev',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 3,
    fullName: 'O‘ktamova Zilola O‘ktam qizi',
    group: '11-01-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998900010003',
    supervisorName: 'B.Abdullayev',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 4,
    fullName: 'Hazratqulova Ro’zigul Qurbonali qizi',
    group: '11.01.25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998947015207',
    supervisorName: 'B.Abdullayev',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 5,
    fullName: 'Julanov Shaxriyor Farhodovich',
    group: '11.01.25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998200297606',
    supervisorName: 'B.Abdullayev',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 6,
    fullName: 'Saydullaev Zoxidjon Farhod o‘g‘li',
    group: '11-01-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998948903730',
    supervisorName: 'B.Abdullayev',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 7,
    fullName: 'Adhamov Tohir Zokir o‘g‘li',
    group: '11-01-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998333350077',
    supervisorName: 'B.Abdullayev',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 8,
    fullName: 'Tuxtaboyev Ibroxim Muhiddin o‘g‘li',
    group: '12.01.25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998772694802',
    supervisorName: 'B.Abdullayev',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 9,
    fullName: 'Dangalova Madina Amrullayevna',
    group: 'M301-24',
    courseStr: '2-kurs (magistratura)',
    course: 2,
    phone: '+998943256465',
    supervisorName: 'B.Jumayev',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 10,
    fullName: 'Tursunov Og‘abek Ikrom o‘g‘li',
    group: '901-23',
    courseStr: '4-kurs',
    course: 4,
    phone: '+998889770723',
    supervisorName: 'D.Shomurodov',
    facultyOrField: 'Iqtisodiyot',
  },
  {
    row: 11,
    fullName: 'Rayimqulov Xojiakbar Gʻulomjon oʻgʻli',
    group: '12.01.25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998502306507',
    supervisorName: 'B.Abdullayev',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 12,
    fullName: 'Yaxshilikova Zilola Baxtiyor qizi',
    group: '502-24',
    courseStr: '3-kurs',
    course: 3,
    phone: '+998944582004',
    supervisorName: 'S.O‘rinboyeva',
    facultyOrField: 'Menejment',
  },
  {
    row: 13,
    fullName: 'Xidirov Shokirbek Shuhrat oʻgʻli',
    group: '401.24',
    courseStr: '3-kurs',
    course: 3,
    phone: '+998773857579',
    supervisorName: 'E.Mamarasulov',
    facultyOrField: 'Oziq-ovqat texnologiyasi',
  },
  {
    row: 14,
    fullName: 'Onorboyev Kamronbek Qoplonbek o‘g‘li',
    group: '11.01.25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998934840525',
    supervisorName: 'B.Abdullayev',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 15,
    fullName: 'Qarshibayeva Diyora Xusanboy qizi',
    group: 'M 101-25',
    courseStr: '1-kurs (magistratura)',
    course: 1,
    phone: '+998940161252',
    supervisorName: 'M.Mavlonov',
    facultyOrField: 'Biotexnologiya',
  },
  {
    row: 16,
    fullName: 'Xikmatova Saida Qudratilla qizi',
    group: '402.25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998977651224',
    supervisorName: 'M.Mavlonov',
    facultyOrField: 'Oziq-ovqat texnologiyasi',
  },
  {
    row: 17,
    fullName: 'Omanov Foziljon O‘tkir o‘g‘li',
    group: '901-24',
    courseStr: '3-kurs',
    course: 3,
    phone: '+998934495250',
    supervisorName: 'I.Turdiqulov',
    facultyOrField: 'Iqtisodiyot',
  },
  {
    row: 18,
    fullName: 'Abduvaliyeva Hilola Rahim qizi',
    group: '501-22',
    courseStr: '5-kurs',
    course: 5,
    phone: '+998501114640',
    supervisorName: 'M.Mavlonov',
    facultyOrField: 'Oziq-ovqat texnologiyasi',
  },
  {
    row: 19,
    fullName: 'Toirov Roʻzimat Maxmud oʻgʻli',
    group: '301-23',
    courseStr: '4-kurs',
    course: 4,
    phone: '+998990067518',
    supervisorName: 'U.Turdiyev',
    facultyOrField: 'Texnologik jarayonlar va ishlab chiqarishni avtomatlashtirish',
  },
  {
    row: 20,
    fullName: 'Samidli Jalaladdin Mushviq og‘lu',
    group: '11.01.25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998900010020',
    supervisorName: 'B.Abdullayev',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 21,
    fullName: 'Tursunboyev Abdulvohid Azimjon o‘g‘li',
    group: '701-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998949981914',
    supervisorName: 'D.Bobonov',
    facultyOrField: 'Menejment',
  },
  {
    row: 22,
    fullName: 'Xolmominov Shodiyor Jaloliddin o‘g‘li',
    group: '11.01.25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998900010022',
    supervisorName: 'B.Abdullayev',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 23,
    fullName: 'Bobojonov Hayotbek Abdukarim o‘g‘li',
    group: '15.01.25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998948827303',
    supervisorName: 'A.Norboyev',
    facultyOrField: 'Mashinasozlik va mexanika',
  },
  {
    row: 24,
    fullName: 'Xamraqulova Gulsevar Xazratqul qizi',
    group: '402.25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998501854327',
    supervisorName: 'M.Mavlonov',
    facultyOrField: 'Oziq-ovqat texnologiyasi',
  },
  {
    row: 25,
    fullName: 'Toʻraqulov Ahadbek Neʼmatjon oʻgʻli',
    group: '601-24',
    courseStr: '3-kurs',
    course: 3,
    phone: '+998973447705',
    supervisorName: 'U.Turdiyev',
    facultyOrField: 'Texnologik jarayonlar va ishlab chiqarishni avtomatlashtirish',
  },
  {
    row: 26,
    fullName: 'Nasridenov Quvonchbek Tuxtamurod o’g’li',
    group: '801-23',
    courseStr: '4-kurs',
    course: 4,
    phone: '+998933130178',
    supervisorName: 'U.Turdiyev',
    facultyOrField: 'Texnologik mashinalar va jihozlar',
  },
  {
    row: 27,
    fullName: 'Gʻaniyev Komiljon Yorqinovich',
    group: '601-24',
    courseStr: '3-kurs',
    course: 3,
    phone: '+998937107701',
    supervisorName: 'S.Abdurahmonova',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 28,
    fullName: 'Nabiyev Sardorbek Iqboljon oʻgʻli',
    group: '401-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998905866795',
    supervisorName: 'F.Rahmatov',
    facultyOrField: 'Oziq-ovqat texnologiyasi',
  },
  {
    row: 29,
    fullName: 'To‘rayev Dilshod Shuhrat o‘g‘li',
    group: '702-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998954560222',
    supervisorName: 'Sh.Utkirov',
    facultyOrField: 'Menejment',
  },
  {
    row: 30,
    fullName: 'Shamsiddinov Rustambek Gʻaybulla oʻgʻli',
    group: '401-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998949370315',
    supervisorName: 'S.Abdurahmonova',
    facultyOrField: 'Oziq-ovqat texnologiyasi',
  },
  {
    row: 31,
    fullName: 'Inadullayev Javohir Ilyos o‘g‘li',
    group: '13.01.25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998917111445',
    supervisorName: 'B.Jumayev',
    facultyOrField: 'Biotexnologiya',
  },
  {
    row: 32,
    fullName: 'Yo‘ldosheva Madina Ahmad qizi',
    group: '401-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998880060427',
    supervisorName: 'M.Mavlonov',
    facultyOrField: 'Oziq-ovqat texnologiyasi',
  },
  {
    row: 33,
    fullName: 'Madusmonova Zilola Abdunazar qizi',
    group: '401-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998505900107',
    supervisorName: 'M.Mavlonov',
    facultyOrField: 'Oziq-ovqat texnologiyasi',
  },
  {
    row: 34,
    fullName: 'Umaraliyev Azizbek Akram oʻgʻli',
    group: '502-23',
    courseStr: '4-kurs',
    course: 4,
    phone: '+998900040630',
    supervisorName: 'B.Jumayev',
    facultyOrField: 'Menejment',
  },
  {
    row: 35,
    fullName: 'Anvarov Jasurbek Jamshidbek oʻgʻli',
    group: '502-23',
    courseStr: '4-kurs',
    course: 4,
    phone: '+998933844442',
    supervisorName: 'F.Rahmatov',
    facultyOrField: 'Menejment',
  },
  {
    row: 36,
    fullName: 'Baxtiyorova Muxlisa Poʻlat qizi',
    group: '13-01-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998505021829',
    supervisorName: 'M.Mavlonov',
    facultyOrField: 'Biotexnologiya',
  },
  {
    row: 37,
    fullName: 'Abdikaxarova Madina Axmad qizi',
    group: '13.01.25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998879613707',
    supervisorName: 'M.Mavlonov',
    facultyOrField: 'Biotexnologiya',
  },
  {
    row: 38,
    fullName: 'Toʻraboyev Iskandar Baxtiyor oʻgʻli',
    group: '102-25 M',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998507037031',
    supervisorName: 'A.Eminov',
    facultyOrField: 'Kimyo muhandisligi',
  },
  {
    row: 39,
    fullName: 'Rahmonova Laylo Abbos qizi',
    group: '702-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998956244164',
    supervisorName: 'S.Abdurahmonova',
    facultyOrField: 'Menejment',
  },
  {
    row: 41,
    fullName: 'Abdumalikov Dilshod Ravshan o‘g‘li',
    group: '901-23',
    courseStr: '4-kurs',
    course: 4,
    phone: '+998934945704',
    supervisorName: 'S.Abdurahmonova',
    facultyOrField: 'Iqtisodiyot',
  },
  {
    row: 42,
    fullName: 'Burxonov Akmaljon Xamidovich',
    group: 'S 602-21',
    courseStr: '4-kurs',
    course: 4,
    phone: '+998990089688',
    supervisorName: 'M.Mavlonov',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 44,
    fullName: 'Abdunabiyeva Habiba Alisher qizi',
    group: '402-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998930497444',
    supervisorName: 'M.Mavlonov',
    facultyOrField: 'Oziq-ovqat texnologiyasi',
  },
  {
    row: 45,
    fullName: 'Quvanova Rahima Sobirjon qizi',
    group: '401-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998881741006',
    supervisorName: 'M.Sobirova',
    facultyOrField: 'Oziq-ovqat texnologiyasi',
  },
  {
    row: 46,
    fullName: 'Nurmetov Hayot Baxodir o‘g‘li',
    group: '601-24',
    courseStr: '3-kurs',
    course: 3,
    phone: '+998992760261',
    supervisorName: 'D.Bobonov',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 47,
    fullName: 'Jarkinboyeva Zuhra Sharofiddin qizi',
    group: '901-23',
    courseStr: '4-kurs',
    course: 4,
    phone: '+998950077382',
    supervisorName: 'D.Shodmonqulov',
    facultyOrField: 'Iqtisodiyot',
  },
  {
    row: 48,
    fullName: 'Abduxakimov Ozodbek Ashraf o‘g‘li',
    group: '601-24',
    courseStr: '3-kurs',
    course: 3,
    phone: '+998507008486',
    supervisorName: 'Sh.Utkirov',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 49,
    fullName: 'Toʻrayeva Marjona Yoʻlchi qizi',
    group: '11-01-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998501905867',
    supervisorName: 'B.Abdullayev',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 50,
    fullName: 'Saydullayev Asadbek Xayrulla oʻgʻli',
    group: '11.01.25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998950963307',
    supervisorName: 'B.Abdullayev',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 51,
    fullName: 'Karimova Gulnora Raxmatula qizi',
    group: '12 01 25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998978350906',
    supervisorName: 'B.Abdullayev',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 53,
    fullName: 'Qarshiboyev Shahboz Aktam oʻgʻli',
    group: '12-01-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998956306366',
    supervisorName: 'B.Abdullayev',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 54,
    fullName: 'Xolmurodov Ogʻabek Toshbolta oʻgʻli',
    group: '201-24',
    courseStr: '3-kurs',
    course: 3,
    phone: '+998973152706',
    supervisorName: 'A.Norboyev',
    facultyOrField: 'Texnologik mashinalar va jihozlar',
  },
  {
    row: 55,
    fullName: 'Nazarov Javohir Ro‘zimurod o‘g‘li',
    group: '502-24',
    courseStr: '3-kurs',
    course: 3,
    phone: '+998919860441',
    supervisorName: 'N.Azamqulov',
    facultyOrField: 'Menejment',
  },
  {
    row: 56,
    fullName: 'Suyunov Begzodjon',
    group: '14 01 25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998930493907',
    supervisorName: 'U.Bababekov',
    facultyOrField: 'Kimyo muhandisligi',
  },
  {
    row: 57,
    fullName: 'Berdiqulov Sunnat Inomjonvich',
    group: '14.01.25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998940650615',
    supervisorName: 'U.Bababekov',
    facultyOrField: 'Kimyo muhandisligi',
  },
  {
    row: 59,
    fullName: 'Sobirov Asror Ismatulla oʻgʻli',
    group: '601-24',
    courseStr: '3-kurs',
    course: 3,
    phone: '+998919496506',
    supervisorName: 'D.Bobonov',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 61,
    fullName: 'Sattiyev Saidabbos Azizillo oʻgʻli',
    group: '201-24',
    courseStr: '3-kurs',
    course: 3,
    phone: '+998930364377',
    supervisorName: 'A.Norboyev',
    facultyOrField: 'Texnologik mashinalar va jihozlar',
  },
  {
    row: 62,
    fullName: 'Mirsharaf Xolmuminov Orif oʻgʻli',
    group: '801-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998945674022',
    supervisorName: 'B.Abdullayev',
    facultyOrField: 'Texnologik mashinalar va jihozlar',
  },
  {
    row: 64,
    fullName: 'Omonboyev Nodir Akmal oʻgʻli',
    group: '502-23',
    courseStr: '4-kurs',
    course: 4,
    phone: '+998940082708',
    supervisorName: 'M.Mavlonov',
    facultyOrField: 'Menejment',
  },
  {
    row: 65,
    fullName: 'Korabekova Gulnoza Shuxrat qizi',
    group: 'M 501-25',
    courseStr: '1-kurs (magistratura)',
    course: 1,
    phone: '+998953661166',
    supervisorName: 'S.Abdurahmonova',
    facultyOrField: 'Menejment',
  },
  {
    row: 66,
    fullName: 'Nomonjonova Zaxro Farhodjon qizi',
    group: '11-01-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998900010066',
    supervisorName: 'B.Abdullayev',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 67,
    fullName: 'Mirahmatov Farrux Farhod oʻgʻli',
    group: '11-01-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998900010067',
    supervisorName: 'B.Abdullayev',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 68,
    fullName: 'Qochqaorova Aziza Zokir qizi',
    group: '102-24',
    courseStr: '3-kurs',
    course: 3,
    phone: '+998900010068',
    supervisorName: 'M.Nosirov',
    facultyOrField: 'Kimyo muhandisligi',
  },
  {
    row: 69,
    fullName: 'Sherzotov Nazarbek Sherzod oʻgʻli',
    group: '11-01-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998900010069',
    supervisorName: 'B.Abdullayev',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 70,
    fullName: 'Kamoliddinov Muhiddin G‘aybiddin oʻgʻli',
    group: '11-01-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998900010070',
    supervisorName: 'B.Abdullayev',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 71,
    fullName: 'Qurbonboyeva Maftuna Sapar qizi',
    group: '401-23',
    courseStr: '4-kurs',
    course: 4,
    phone: '+998900010071',
    supervisorName: 'A.Sangirov',
    facultyOrField: 'Texnologik jarayonlar va ishlab chiqarishni avtomatlashtirish',
  },
  {
    row: 72,
    fullName: 'Maxmanazarov Sardor Toirjon o‘g‘li',
    group: '201.24',
    courseStr: '3-kurs',
    course: 3,
    phone: '+998200156772',
    supervisorName: 'A.Sangirov',
    facultyOrField: 'Texnologik mashinalar va jihozlar',
  },
  {
    row: 73,
    fullName: 'Xolyigitov Abbos G‘anisher o‘g‘li',
    group: '301-24',
    courseStr: '3-kurs',
    course: 3,
    phone: '+998900010073',
    supervisorName: 'A.Sangirov',
    facultyOrField: 'Texnologik jarayonlar va ishlab chiqarishni avtomatlashtirish',
  },
  {
    row: 74,
    fullName: 'Omonqulov Asadbek Asqar o‘g‘li',
    group: '801-23',
    courseStr: '4-kurs',
    course: 4,
    phone: '+998900010074',
    supervisorName: 'Sh.Utkirov',
    facultyOrField: 'Texnologik mashinalar va jihozlar',
  },
  {
    row: 75,
    fullName: 'Alisherova Gulbaxor Alisher qizi',
    group: '5-01-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998900010075',
    supervisorName: 'A.Sangirov',
    facultyOrField: 'Menejment',
  },
  {
    row: 76,
    fullName: 'Muhiddinov Muhriddin Zuhriddin oʻgʻli',
    group: '12-01-25',
    courseStr: '2-kurs',
    course: 2,
    phone: '+998900010076',
    supervisorName: 'B.Abdullayev',
    facultyOrField: 'Kompyuter injiniringi',
  },
  {
    row: 77,
    fullName: 'Jalilov Zayniddin Shuhrat oʻgʻli',
    group: '201-23',
    courseStr: '4-kurs',
    course: 4,
    phone: '+998919731713',
    supervisorName: 'M.Nosirov',
    facultyOrField: 'Texnologik mashinalar va jihozlar',
  },
];
